import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import MessageBox from "./components/MessageBox";

export default function Home() {
  const [msgstate, setMsgstate] = useState<
    {
      msg: string;
      author: "AI" | "user";
    }[]
  >([
    {
      msg: "Hello!",
      author: "AI",
    },
  ]);

  const [inputState, setInputState] = useState("");

  useEffect(() => {
    const ask = async () => {
      console.log(inputState);
      const data = await fetch("/ask", {
        headers: {
          "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
          pragma: "no-cache",
        },
        body: `msg=${inputState}`,
        method: "POST",
      });
      setMsgstate([...msgstate, { msg: await data.text(), author: "AI" }]);

      setInputState("");
    };

    if (msgstate[msgstate.length - 1].author == "user") {
      ask();
    }
  }, [msgstate, inputState]);

  return (
    <div>
      <Head>
        <title>정보사사반(3팀) 중간발표 시연</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full max-w-5xl px-6 pb-16 mt-16 mx-auto text-center">
        <h1 className="text-4xl font-bold">
          2022년 정보사사반(3팀) 중간발표 시연
        </h1>
        {/* {JSON.stringify(msgstate)} */}

        <div className="p-6 bg-slate-50 shadow-xl relative min-h-[28rem] text-xl rounded-xl border border-slate-200 mt-8">
          <div className="flex flex-col gap-4 relative pb-16">
            {msgstate.map((m, i) => {
              return <MessageBox key={i} text={m.msg} author={m.author} />;
            })}
          </div>
          <div className="absolute bottom-4 inset-x-4 flex items-center gap-2">
            <input
              value={inputState}
              className="p-4 shadow-sm rounded-md h-10 w-full  outline-none ring-1 ring-slate-50 transition text-lg hover:shadow-lg"
              placeholder="질문을 입력해 주세요..."
              onChange={(e) => {
                setInputState(e.target.value);
              }}
            />
            <button
              onClick={async () => {
                if (inputState != "") {
                  setMsgstate([
                    ...msgstate,
                    { msg: inputState, author: "user" },
                  ]);
                }
              }}
              className="rounded-md whitespace-nowrap h-10 px-6 flex items-center font-medium shadow-lg transition  text-white hover:bg-blue-500 bg-black hover:scale-105"
            >
              보내기
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
